### ISSUE TITLE
Error using griddedInterpolant

### ISSUE THREAD

**Issue by HannahBuckland** [e5k/TOTGS#1]
(Executing in MATLAB 2018a, on Macbook running macOS Mojave).

I am trying to run TOTGS with the example files included.  I get as far as adding the zero line, but the code doesn't execute beyond plotting the Voronoi and I get this error:

```
Error using griddedInterpolant
The grid vectors must contain unique points.

Error in interp1 (line 151)
        F = griddedInterpolant(X,V,method);

Error in TOTGS>res_voron (line 593)
gs_50       = interp1(cum, tr.pClass, .50);       % Median GS

Error in TOTGS>Voronoi_TOTGS (line 567)
res_voron(vorWt);
 
Error while evaluating UIControl Callback.
```

I have also tried running it with my own dataset, which has the zero line as points in the input file, but I run into the same error.  Has anyone else come across this issue and found a solution?

**Comment by e5k** [comment]
Probably due to an update to 2018. Just pushed a new commit that should solve the problem.
[18e2304a8c26ba99396449f04dcec50ac244d944](https://github.com/e5k/TOTGS/commit/18e2304a8c26ba99396449f04dcec50ac244d944)

**Comment by HannahBuckland** [comment]
Great, now executing with no problems! Thank you for the quick response, HB.
